// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbvjddpdeuypcsvzcahh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNidmpkZHBkZXV5cGNzdnpjYWhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzOTY5OTcsImV4cCI6MjA2Njk3Mjk5N30.r8tx0T_BqMdUWnZJs6XNpijvPdxL9SP3v4cVJiNKy20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});